[deploy]
include = [
  "dist/*", # include all files and subdirs in static/
  "asyncapi.yaml", # include AsyncAPI YAML spec
  "asyncapi.json", # include AsyncAPI JSON spec
]

[build]
assets = [
  "dist/*", # include build assets
  "asyncapi.yaml", # include AsyncAPI YAML spec
  "asyncapi.json", # include AsyncAPI JSON spec
]
