name: CI (Build, Test, Deploy)

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      tests-passed: ${{ steps.set-output.outputs.tests_passed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install JS deps
        run: pnpm install

      - name: Build backend (release)
        run: cargo build --release

      - name: Install Playwright
        run: pnpm exec playwright install --with-deps chromium

      - name: Generate types and front-end build
        run: pnpm generate-all && pnpm build

      - name: Start backend server
        run: |
          cargo run --release &
          echo $! > backend.pid
        env:
          RUST_LOG: info

      - name: Wait for backend to be ready
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:8000/schemas > /dev/null 2>&1; do sleep 2; done'

      - name: Run Playwright E2E tests
        id: run-tests
        run: pnpm run test:e2e
        env:
          CI: true
        continue-on-error: true

      - name: Set output based on test result
        id: set-output
        run: |
          if [ "${{ steps.run-tests.outcome }}" = "success" ]; then
            echo "tests_passed=true" >> $GITHUB_OUTPUT
          else
            echo "tests_passed=false" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30

      - name: Stop servers
        if: always()
        run: |
          if [ -f backend.pid ]; then
            kill $(cat backend.pid) || true
            rm backend.pid
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: build-test
    if: needs.build-test.outputs.tests-passed == 'true' && github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies (frontend)
        run: pnpm install

      - name: Generate all JS assets (schemas, types, etc.)
        run: pnpm generate-all

      - name: Deploy to Shuttle
        uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01K477CR6MYM0T4YWRC1N4KVQB
